-- | Datastructures and algorithms for k-way merges.
--
-- === TODO
--
-- This is temporary module header documentation. The module will be
-- fleshed out more as we implement bits of it.
--
-- Related work packages: 5, 6
--
-- This module includes in-memory parts for, amongst others,
--
-- * k-way merge data structures (heap or tournament tree)
--
-- * k-way merge algorithms
--
-- The above list is a sketch. Functionality may move around, and the list is
-- not exhaustive.
--
module Database.LSMTree.Internal.KMerge () where
