name: "Print CPU info"
description: "Prints CPU info"
runs:
  using: "composite"
  steps:
    - if: ${{ runner.os == 'macOS' }}
      run: sysctl -a machdep.cpu
      shell: sh

    - if: ${{ runner.os == 'Linux' }}
      run: cat /proc/cpuinfo
      shell: sh

    # TODO: wmic is no longer available by default on Windows, it seems. We should replace it.
    - if: ${{ runner.os == 'Windows' && false }}
      run: wmic cpu get caption, deviceid, name, numberofcores, maxclockspeed, status
      shell: cmd
