name: "Generate README.md"
description: "Generate README.md from the Cabal package description"
inputs:
  ghc-version:
    required: true
    description: "Version of GHC"
  cabal-version:
    required: true
    description: "Version of cabal"
  hackage-index-state:
    required: false
    description: "Timestamp for Hackage index"
runs:
  using: composite
  steps:
    - name: 🛠️ Install Haskell
      uses: haskell-actions/setup@v2
      id: setup-haskell
      with:
        ghc-version: ${{ inputs.ghc-version }}
        cabal-version: ${{ inputs.cabal-version }}

    - name: 💾 Restore Cabal dependencies
      uses: actions/cache/restore@v4
      id: cache-cabal
      with:
        path: ${{ steps.setup-haskell.outputs.cabal-store }}
        key: generate-readme-${{ runner.os }}-ghc-${{ steps.setup-haskell.outputs.ghc-version }}-cabal-${{ steps.setup-haskell.outputs.cabal-version }}

    - name: 🛠️ Generate README.md
      run: ./scripts/generate-readme.hs
      shell: sh

    - name: 💾 Save Cabal dependencies
      uses: actions/cache/save@v4
      if: ${{ !env.ACT && steps.cache-cabal.outputs.cache-hit != 'true' }}
      with:
        path: ${{ steps.setup-haskell.outputs.cabal-store }}
        key: ${{ steps.cache-cabal.outputs.cache-primary-key }}
