name: "Configure Fast APT Mirror"
description: "Configure Fast APT Mirror"
runs:
  using: composite
  steps:
    # Some mirrors for the Ubuntu software repositories, like Microsoft
    # Azure-hosted ones, are sometimes unstable. This is a known issue (see links
    # below). This can cause apt-get commands to be prohibitively slow, causing CI
    # jobs to time out. We use fast-apt-mirror to pick suitable alternative
    # mirrors.
    #
    # <https://github.com/actions/runner-images/issues?q=is%3Aissue+azure.archive.ubuntu.com>
    # <https://github.com/actions/runner-images/issues/12949>
    # <https://github.com/actions/runner-images/issues/7048>
    - name: 🛠️ Configure Fast APT Mirror (Linux)
      if: ${{ runner.os == 'Linux' }}
      uses: vegardit/fast-apt-mirror.sh@v1